### PR TITLE
[ENG-3059] fix: Remove ordinal callout from send rare sats

### PR DESCRIPTION
**Pull request by dhriaznov**
# 🔘 PR Type
What kind of change does this PR introduce?

- [x] Bugfix

# 📜 Background
We should remove the warning callout completely cause this is not a ordinal that is is being sent.

Issue Link: #[[ENG-3059](https://linear.app/xverseapp/issue/ENG-3059/remove-ordinal-callout-from-send-rare-sats)]
Context Link (if applicable):

# 🔄 Changes
- Hid the ordinal callout on the rare sats sending screen
- Updated the look of the validation error for the send form component according to our design guideline: https://zeroheight.com/0683c9fa7/p/76af35-form/b/663535
- Fixed the "Next" button on the sending screen to make it actually disabled instead of just being grayed out (https://secretkeylabs.slack.com/archives/C05QCJNT95E/p1697716747041659)
- Added rare sats-related info message from the design (https://www.figma.com/file/FCk8jDMsC8UEfPSWnqewLY/Xverse-%E2%80%94-Extension-V2?type=design&node-id=9071-35537&mode=design&t=ufoJEpudkyIJh6nR-0)
- Fixed a small typo in the copy

Impact:
- This PR impacts the rare sats sending screen and the send form component which is used on other tokens sending screens

# 🖼 Screenshot / 📹 Video
Monosnap Monosnap 2023-10-19 14-38-28

Monosnap Monosnap 2023-10-19 14-38-34

Monosnap Monosnap 2023-10-24 13-32-55

# ✅ Review checklist
Please ensure the following are true before merging:

- [ ] Code Style is consistent with the project guidelines.
- [ ] Code is readable and well-commented.
- [ ] No unnecessary or debugging code has been added.
- [ ] Security considerations have been taken into account.
- [ ] The change has been manually tested and works as expected.
- [ ] Breaking changes and their impacts have been considered and documented.
- [ ] Code does not introduce new technical debt or issues.

### CODE REVIEW

**Review by victorkirov — APPROVED** [review]
Noice!

**Comment by blehitsahmad** [comment]
@dhriaznov 
"Added rare sats-related info message from the design" - could you please explain this change?

**Comment by blehitsahmad** [comment]
@dhriaznov left a [comment](https://linear.app/xverseapp/issue/ENG-3059/remove-ordinal-callout-from-send-rare-sats#comment-410d5cc1) in the linear ticket. Also kindly look into my previous comment for scope definition.

**Comment by dhriaznov** [comment]
I added a small update after Ahmad's comment, could you retake a look please @victorkirov ?

**Comment by dhriaznov** [comment]
> @dhriaznov "Added rare sats-related info message from the design" - could you please explain this change?

I meant this one:
Monosnap Xverse — Extension V2 – Figma 2023-10-24 19-15-55

Added the figma link to PR description

**Comment by blehitsahmad** [comment]
@dhriaznov this is good to merge -- left [a comment](https://linear.app/xverseapp/issue/ENG-3059/remove-ordinal-callout-from-send-rare-sats#comment-a2e3d0e9) in the PR as well with references

**Review by DuskaT021 — APPROVED** [review]

**Pull request merged**
