### PR TITLE
refactor: updated ordinals tx functions

### PR DESCRIPTION
**Pull request by abdulhaseeb4239**
# 🔘 PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Enhancement
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

# 📜 Background
Moved ordinal transactions logic to xverse-core

Issue Link: https://linear.app/xverseapp/issue/ENG-2551/updated-functions-for-ordinal-transactions
Context Link (if applicable): https://linear.app/xverseapp/issue/ENG-2528/move-ordinal-transactions-logic-to-xverse-core

# 🔄 Changes
Updated ordinals transactions functions from xverse-core
This PR depends on xverse-core PR https://github.com/secretkeylabs/xverse-core/pull/218

Impact:
- Send Ordinal, Restore Ordinal

Testing:
I have tested send Ordinal and recover Ordinal flow on iOS simulator. 

Testing Instruction: 

- Make sure Send Ordinal from collectibles is working fine including the fee calculation edit
- Make sure Recover Ordinals flow from settings is working fine including the fee calculation and fee edit

# 🖼 Screenshot / 📹 Video

https://github.com/secretkeylabs/xverse-web-extension/assets/29428363/af9dff1f-a479-471c-8950-4420df3b5df0

# ✅ Review checklist
Please ensure the following are true before merging:

- [x] Code Style is consistent with the project guidelines.
- [x] Code is readable and well-commented.
- [x] No unnecessary or debugging code has been added.
- [x] Security considerations have been taken into account.
- [x] The change has been manually tested and works as expected.
- [x] Breaking changes and their impacts have been considered and documented.
- [x] Code does not introduce new technical debt or issues.

### CODE REVIEW

**Comment by teebszet** [comment]
code looks good, but missing videos or details of local tests.

**Comment by DuskaT021** [comment]
has conflicts

**Comment by teebszet** [comment]
manually tested too. lgtm

**Review by teebszet — DISMISSED** [review]

**Review by teebszet — APPROVED** [review]

**Comment by teebszet** [comment]
@abdulhaseeb4239 the recover flow wasn't working? pr has conflicts again

**Comment by abdulhaseeb4239** [comment]
> @abdulhaseeb4239 the recover flow wasn't working? pr has conflicts again

yes, it was not working properly. the ordinal UTXOs were not being fetched from API to filter UTXOs from fees. The change is in core

**Review by teebszet — DISMISSED** [review]

**Comment by DuskaT021** [comment]
will be picked up when the core pr gets approved @teebszet

**Comment by DuskaT021** [comment]
I'll be testing this pr with the latest xverse-core https://github.com/secretkeylabs/xverse-core/releases/latest at the time of writing it was 1.6.5

**Comment by DuskaT021** [comment]
left my findings in the linear ticket ENG-2551

**Comment by DuskaT021** [comment]
> manually tested. send ordinal flow looks good, but recover ordinal looks broken:
> 
> image

it is still broken

**Review by teebszet — DISMISSED** [review]

**Comment by teebszet** [comment]
@DuskaT021 was this one ready to merge? I can't remember if it was on a discord thread

**Comment by DuskaT021** [comment]
> @DuskaT021 was this one ready to merge? I can't remember if it was on a discord thread

it was in linear [here](https://linear.app/xverseapp/issue/ENG-2551#comment-fe9c9158) - not ready for merge, needs to be retested, after the xverse-core updated

**Comment by DuskaT021** [comment]
@abdulhaseeb4239 needs conflicts resolved

**Comment by abdulhaseeb4239** [comment]
> @abdulhaseeb4239 needs conflicts resolved

done

**Review by teebszet — APPROVED** [review]

**Comment by DuskaT021** [comment]
left a comment in the linear ticket @abdulhaseeb4239

**Pull request closed without merging**
