### PR TITLE
Show BRC20 token transaction history

### PR DESCRIPTION
**Pull request by Imamah-Zafar**
# 🔘 PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

# 📜 Background
Show BRC20 token transaction history

Issue Link: [#[ENG-2459]](https://linear.app/xverseapp/issue/ENG-2459/brc-20-display-transaction-history)

# 🔄 Changes
Depends on changes added in the [core PR ](https://github.com/secretkeylabs/xverse-core/pull/247)
We use the hiro api from the xverse api to get the transaction history of user's tokens. The transaction History components  which were being used to display BTC transaction history and stacks token transactions history, are updated in this PR to accept BRC20transaction history along with the rest of the coins. 
The pending state of brc20 transaction is also not handled by this PR as hiro api does not support this 

Incase of an error fetching data of an token we have an error message which is displayed

# 🖼 Screenshot / 📹 Video

error-state

# ✅ Review checklist
Please ensure the following are true before merging:

- [x] Code Style is consistent with the project guidelines.
- [x] Code is readable and well-commented.
- [x] No unnecessary or debugging code has been added.
- [x] Security considerations have been taken into account.
- [x] The change has been manually tested and works as expected.
- [x] Breaking changes and their impacts have been considered and documented.
- [x] Code does not introduce new technical debt or issues.

### CODE REVIEW

**Review by dhriaznov — APPROVED** [review]
LGTM

**Review by dhriaznov — DISMISSED** [review]

**Review by dhriaznov — DISMISSED** [review]

**Review by dhriaznov — APPROVED** [review]
LGTM

**Comment by DuskaT021** [comment]
left a comment in [linear](https://linear.app/xverseapp/issue/ENG-2459/brc-20-display-transaction-history#comment-20726d6b)

**Review by dhriaznov — DISMISSED** [review]

**Review by DuskaT021 — APPROVED** [review]

**Comment by teebszet** [comment]
💩 this PR contains a large package-lock.json diff @Imamah-Zafar @dhriaznov . need to watch out for those and remember the github UI hides it by default. 

I'm in the process of creating the next release candidate, and see these in the merge conflicts 🥲

**Comment by Imamah-Zafar** [comment]
> 💩 this PR contains a large package-lock.json diff @Imamah-Zafar @dhriaznov . need to watch out for those and remember the github UI hides it by default.
> 
> I'm in the process of creating the next release candidate, and see these in the merge conflicts 🥲

my bad would be extra careful about this in the future

**Pull request merged**
