### PR TITLE
Handle gaia hub migration

### PR DESCRIPTION
**Pull request by m-aboelenein**
# 🔘 PR Type
What kind of change does this PR introduce?

changing the gaia hub url

- [ ] Bugfix
- [x] Enhancement
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

# 📜 Background

due to Hiro migrating their Gaia hub to a new provider and domain, we need to point to the new provider url 

# 🔄 Changes
Does this PR introduce a breaking change?

- [ ] Yes, Incompatible API changes
- [x] No, Adds functionality (backwards compatible)
- [ ] No, Bug fixes (backwards compatible)

Changes:
- gaia hub provider url

Impact:
- might have impact on account restoration until Gaia is fully migrated

affect Modules are: 
- Restore Wallet accounts
- create wallet account
- change network

# ✅ Review checklist
Please ensure the following are true before merging:

- [ ] Code Style is consistent with the project guidelines.
- [ ] Code is readable and well-commented.
- [ ] No unnecessary or debugging code has been added.
- [ ] Security considerations have been taken into account.
- [ ] The change has been manually tested and works as expected.
- [ ] Breaking changes and their impacts have been considered and documented.
- [ ] Code does not introduce new technical debt or issues.

### CODE REVIEW

**Comment by m-aboelenein** [comment]
This is a placeholder branch for testing this PR on core https://github.com/secretkeylabs/xverse-core/pull/214

**Comment by DuskaT021** [comment]
@m-aboelenein should we resolve the conflicts?

**Comment by blehitsahmad** [comment]
@m-aboelenein this PR is running ext version 0.15.0 while we are running version 0.19.0 currently. I am currently testing with the available version, but I think it would be better if we could update it to the latest.

**Comment by m-aboelenein** [comment]
> @m-aboelenein this PR is running ext version 0.15.0 while we are running version 0.19.0 currently. I am currently testing with the available version, but I think it would be better if we could update it to the latest.

Done

**Comment by blehitsahmad** [comment]
@m-aboelenein good to go, [commented](https://linear.app/xverseapp/issue/ENG-2426/handle-gaia-hub-host-migration-for-wallet-config#comment-ad727aad) on the linear ticket.

**Review by teebszet — APPROVED** [review]

**Comment by teebszet** [comment]
@DuskaT021 let's also merge this into the rc, as I don't want to risk breaking develop branch until it's well tested with the seed vault

**Pull request merged**
