### PR TITLE
Use updated type from sats-connect

### PR DESCRIPTION
**Pull request by Imamah-Zafar**
# 🔘 PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Enhancement
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

# 📜 Background
In the latest develop version of sats-connect, we have changed the type name from `AddressPurposes` to `AddressPurpose`. Currently the extension wont work with the updated version of sats connect. 

Issue Link: [#[issue_number]](https://linear.app/xverseapp/issue/ENG-2539/fix-typing-issues-due-to-sats-connect-v050)
Context Link (if applicable):

# 🔄 Changes
The PR updates the type name to be used with sats-connect

# 🖼 Screenshot / 📹 Video
Include screenshots or a video demonstrating the changes. This is especially helpful for UI changes.

# ✅ Review checklist
Please ensure the following are true before merging:

- [x] Code Style is consistent with the project guidelines.
- [x] Code is readable and well-commented.
- [x] No unnecessary or debugging code has been added.
- [x] Security considerations have been taken into account.
- [x] The change has been manually tested and works as expected.
- [x] Breaking changes and their impacts have been considered and documented.
- [x] Code does not introduce new technical debt or issues.

### CODE REVIEW

**Review by teebszet — APPROVED** [review]
lgtm

**Comment by yknl** [comment]
What are the testing instructions for this @Imamah-Zafar

**Comment by Imamah-Zafar** [comment]
> What are the testing instructions for this @Imamah-Zafar

To test try running this PR with develop of sats-connect and see if the `connect` function call to log in the user works fine.

**Comment by yknl** [comment]
> To test try running this PR with develop of sats-connect and see if the `connect` function call to log in the user works fine.

What about the sats connect test app? What version is needed? Please provide the detailed testing instructions.

**Comment by Imamah-Zafar** [comment]
> > To test try running this PR with develop of sats-connect and see if the `connect` function call to log in the user works fine.
> 
> What about the sats connect test app? What version is needed? Please provide the detailed testing instructions.

To test this PR:

- Run the develop branch of sats-connect locally 
- Switch to branch `main` of sats-connect test app and update the package.json of sats-connect test app to use the local running version of sats-connect 
- Switch to branch `imamahzafar/eng-2539-fix-typing-issues-due-to-sats-connect-v050` of extension and update the package.json of extension to use the local running version of sats-connect 
- Then try calling the `Connect` function from test app to see if you're able to login successfully.

**Comment by teebszet** [comment]
this is pending a version bump to sats-connect v1.0.0-rc.1 prerelease

**Comment by DuskaT021** [comment]
> this is pending a version bump to sats-connect v1.0.0-rc.1 prerelease

do I update for testing purposes to this version of sats-connect: `sats-connect v1.0.0-rc.1`
@teebszet

**Comment by teebszet** [comment]
@DuskaT021 I just bumped this branch to sats-connect@1.0.0, so you can test on here

**Comment by DuskaT021** [comment]
tested ✅

**Comment by teebszet** [comment]
@Imamah-Zafar could you please check the github build log and fix the error seen there with react-is?

**Review by teebszet — APPROVED** [review]

**Pull request merged**
