### PR TITLE
chore(deps): upgrade `alex-sdk` to 0.1.25

### PR DESCRIPTION
**Pull request by 52**
# 🔘 PR Type
What kind of change does this PR introduce?

- [x] Enhancement

# 📜 Background
The alex-sdk has added support for new tokens, most notably `LEO` & `MEGA` (https://github.com/alexgo-io/alex-sdk/commit/9839433276bcc2acf3eb69442501f5cd64c134df)
This PR upgrades the package version with the motivation to enable in-wallet swaps with these assets.

# 🔄 Changes
- Upgraded `alex-sdk` to `0.1.24`

### CODE REVIEW

**Comment by 52** [comment]
**Note**: Supporting swaps with these assets seems blocked by https://github.com/hirosystems/token-metadata-api/issues/196

**Comment by 52** [comment]
@m-aboelenein This should be ready for review now 👍

**Review by teebszet — APPROVED** [review]
@52 thanks for submitting. I see the latest version is 0.1.26 now with a bug fix

**Comment by DuskaT021** [comment]
making sure it doesn't brake the existing swap logic @rektbap

**Comment by teebszet** [comment]
already upgraded

**Pull request closed without merging**
